language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# PyCrypto does not support PyPy yet.
# See https://github.com/dlitz/pycrypto/pull/59
#  - "pypy"
script: python setup.py test
